version: '3.8'
services:
  ticketservice:
    build:
      context: ./TicketService
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Gerekirse diğer ortam değişkenlerinizi buraya ekleyebilirsiniz.